---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	resolve_data_range(resolve_data_range)
	validate_entities(validate_entities)
	fetch_table_schema(fetch_table_schema)
	SQL_generation(SQL_generation)
	SQL_validation(SQL_validation)
	execute_query(execute_query)
	post_query_operations(post_query_operations)
	business_insight_generator(business_insight_generator)
	format_response_of_business_insight_generator(format_response_of_business_insight_generator)
	__end__([<p>__end__</p>]):::last
	SQL_generation --> SQL_validation;
	SQL_validation -. &nbsp;sql_invalid&nbsp; .-> SQL_generation;
	SQL_validation -. &nbsp;sql_passed&nbsp; .-> execute_query;
	__start__ --> resolve_data_range;
	business_insight_generator --> format_response_of_business_insight_generator;
	execute_query --> post_query_operations;
	fetch_table_schema --> SQL_generation;
	post_query_operations --> business_insight_generator;
	resolve_data_range --> validate_entities;
	validate_entities --> fetch_table_schema;
	format_response_of_business_insight_generator --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
